// List of banned/prohibited medicines for horses in racing
// These medicines require a waiting period before the horse can race again
export const BANNED_MEDICINES = [
  'Phenylbutazone (Bute)',
  'Flunixin Meglumine (Banamine)',
  'Ketoprofen',
  'Diclofenac',
  'Meloxicam',
  'Firocoxib',
  'Corticosteroids (Dexamethasone)',
  'Prednisolone',
  'Methylprednisolone',
  'Triamcinolone',
  'Aminoglycosides (Gentamicin)',
  'Amikacin',
  'Streptomycin',
  'Tetracyclines',
  'Doxycycline',
  'Oxytetracycline',
  'Quinolones (Enrofloxacin)',
  'Ciprofloxacin',
  'Marbofloxacin',
  'Beta-blockers (Propranolol)',
  'Atenolol',
  'Metoprolol',
  'ACE Inhibitors',
  'Enalapril',
  'Benazepril',
  'Diuretics (Furosemide)',
  'Hydrochlorothiazide',
  'Spironolactone',
  'Anabolic Steroids',
  'Boldenone',
  'Stanozolol',
  'Nandrolone',
  'Testosterone',
  'Local Anesthetics (Lidocaine)',
  'Bupivacaine',
  'Mepivacaine',
  'NSAIDs (Non-Steroidal Anti-Inflammatory Drugs)',
  'Aspirin',
  'Naproxen',
  'Ibuprofen',
  'Antibiotics (Penicillin)',
  'Amoxicillin',
  'Cephalexin',
  'Ceftiofur',
  'Antihistamines',
  'Diphenhydramine',
  'Chlorpheniramine',
  'Bronchodilators',
  'Clenbuterol',
  'Albuterol',
  'Theophylline',
  'Muscle Relaxants',
  'Methocarbamol',
  'Carisoprodol',
  'Tranquilizers',
  'Acepromazine',
  'Xylazine',
  'Detomidine',
  'Sedatives',
  'Diazepam',
  'Midazolam',
  'Diğer Yasaklı/Çıkıcı Maddeler',
]

