// Turkish UI Labels and Messages

export const TR = {
  common: {
    save: 'Kaydet',
    cancel: 'İptal',
    delete: 'Sil',
    edit: 'Düzenle',
    add: 'Ekle',
    search: 'Ara',
    filter: 'Filtrele',
    export: 'Dışa Aktar',
    loading: 'Yükleniyor...',
    error: 'Hata',
    success: 'Başarılı',
    confirm: 'Onayla',
    close: 'Kapat',
    back: 'Geri',
    next: 'İleri',
    selectAll: 'Tümünü Seç',
    clear: 'Temizle',
  },
  
  auth: {
    signIn: 'Giriş Yap',
    signOut: 'Çıkış Yap',
    register: 'Kayıt Ol',
    email: 'E-posta',
    password: 'Şifre',
    forgotPassword: 'Şifremi Unuttum',
    rememberMe: 'Beni Hatırla',
    owner: 'Sahip',
    trainer: 'Antrenör',
    selectRole: 'Rolünüzü Seçin',
    fullName: 'Ad Soyad',
    phone: 'Telefon',
    invalidCredentials: 'Geçersiz e-posta veya şifre',
    emailRequired: 'E-posta gerekli',
    passwordRequired: 'Şifre gerekli',
    passwordTooShort: 'Şifre en az 8 karakter olmalı',
  },
  
  nav: {
    home: 'Ana Sayfa',
    horses: 'Atlar',
    expenses: 'Giderler',
    statistics: 'İstatistikler',
    stablemate: 'Eküri',
    billing: 'Faturalandırma',
    settings: 'Ayarlar',
    admin: 'Yönetim',
  },
  
  horses: {
    title: 'Atlar',
    racing: 'Aktif',
    active: 'Aktif',
    stallions: 'Aygırlar',
    foals: 'Taylar',
    mares: 'Kısraklar',
    retired: 'Emekli',
    dead: 'Öldü',
    addHorse: 'At Ekle',
    horseName: 'At Adı',
    status: 'Durum',
    age: 'Yaş',
    yearOfBirth: 'Doğum Yılı',
    racecourse: 'Hipodrom',
    farm: 'Çiftlik',
    trainer: 'Antrenör',
    groom: 'Seyis',
    stable: 'Ahır',
    isRacing: 'Yarışta mı?',
    gender: 'Cinsiyet',
    stallion: 'Aygır',
    mare: 'Kısrak',
    noHorses: 'Henüz at eklenmemiş',
  },
  
  expenses: {
    title: 'Giderler',
    addExpense: 'Gider Ekle',
    listExpenses: 'Giderleri Listele',
    date: 'Tarih',
    category: 'Kategori',
    amount: 'Tutar',
    currency: 'Para Birimi',
    note: 'Not',
    photo: 'Fotoğraf',
    addedBy: 'Ekleyen',
    selectHorses: 'At Seçin',
    selectCategory: 'Kategori Seçin',
    customCategoryName: 'Özel Kategori Adı',
    uploadPhoto: 'Fotoğraf Yükle',
    noExpenses: 'Henüz gider eklenmemiş',
    totalExpenses: 'Toplam Gider',
    monthlyAverage: 'Aylık Ortalama',
    dateRange: 'Tarih Aralığı',
  },
  
  expenseCategories: {
    IDMAN_JOKEYI: 'İdman Jokeyi Ücreti',
    SEYIS: 'Seyis Giderleri',
    ILAC: 'İlaç Giderleri',
    YEM_SAMAN_OT: 'Saman/Ot/Yem Giderleri',
    EKSTRA_ILAC: 'Ekstra İlaç Giderleri',
    YARIS_KAYIT: 'Yarış Kayıt Giderleri',
    NAKLIYE: 'Nakliye (Hipodrom Arası)',
    SEZONLUK_AHIR: 'Sezonluk/Ahır Ücreti',
    OZEL: 'Özel',
  },
  
  statistics: {
    title: 'İstatistikler',
    horsesTab: 'Atlar',
    expensesTab: 'Giderler',
    totalHorses: 'Toplam At',
    horsesByStatus: 'Duruma Göre Atlar',
    horsesByRacecourse: 'Hipodroma Göre Atlar',
    topSpendingHorses: 'En Çok Harcanan Atlar',
    last30Days: 'Son 30 Gün',
    last90Days: 'Son 90 Gün',
    monthlyTotal: 'Aylık Toplam',
    yearlyTotal: 'Yıllık Toplam',
    byCategory: 'Kategoriye Göre',
    perHorseAverage: 'At Başına Ortalama',
    exportCSV: 'CSV Olarak İndir',
  },
  
  // Alias for convenience
  get stats() {
    return this.statistics
  },
  
  stablemate: {
    title: 'Eküri',
    name: 'Eküri Adı',
    foundationYear: 'Kuruluş Yılı',
    coOwners: 'Ortak Sahipler',
    location: 'Konum',
    website: 'Web Sitesi',
    editStablemate: 'Ekürimi Düzenle',
  },
  
  onboarding: {
    welcome: 'Hoş Geldiniz',
    ownerLookup: 'Sahip Adınızı Bulun',
    ownerLookupDesc: 'Lütfen TJK\'daki resmi sahip adınızı yazın',
    searchOwner: 'Sahip Ara',
    selectOwner: 'Sahip Seç',
    setupStablemate: 'Ekürimi Kur',
    setupStablemateDesc: 'Eküri bilgilerinizi girin',
    importHorses: 'Atlarınızı Ekleyin',
    importHorsesDesc: 'TJK\'dan atlarınızı eküriye ekleyin',
    selectHorsesToImport: 'Eklemek istediğiniz atları seçin',
    horseDetails: 'At Detayları',
    finish: 'Tamamla',
  },
  
  billing: {
    title: 'Faturalandırma',
    currentPlan: 'Mevcut Plan',
    nextBilling: 'Sonraki Faturalama',
    manageSubscription: 'Aboneliği Yönet',
    upgrade: 'Yükselt',
    subscriptionStatus: 'Abonelik Durumu',
    active: 'Aktif',
    inactive: 'Pasif',
    expired: 'Süresi Dolmuş',
  },
  
  admin: {
    title: 'Yönetim Paneli',
    users: 'Kullanıcılar',
    horses: 'Atlar',
    referenceData: 'Referans Verileri',
    racecourses: 'Hipodromlar',
    farms: 'Çiftlikler',
    addRacecourse: 'Hipodrom Ekle',
    addFarm: 'Çiftlik Ekle',
    racourseName: 'Hipodrom Adı',
    farmName: 'Çiftlik Adı',
    city: 'Şehir',
  },
  
  validation: {
    required: 'Bu alan gereklidir',
    invalidEmail: 'Geçersiz e-posta adresi',
    passwordTooShort: 'Şifre en az 8 karakter olmalı',
    invalidNumber: 'Geçersiz sayı',
    invalidDate: 'Geçersiz tarih',
    amountMustBePositive: 'Tutar pozitif olmalı',
  },
  
  messages: {
    saveSuccess: 'Başarıyla kaydedildi',
    deleteSuccess: 'Başarıyla silindi',
    updateSuccess: 'Başarıyla güncellendi',
    saveFailed: 'Kaydetme başarısız',
    deleteFailed: 'Silme başarısız',
    updateFailed: 'Güncelleme başarısız',
    loadFailed: 'Yükleme başarısız',
    noPermission: 'Bu işlem için yetkiniz yok',
    confirmDelete: 'Silmek istediğinizden emin misiniz?',
  },
}

export default TR

